### ISSUE TITLE
התראות

### ISSUE THREAD

**Issue by matanrrr** [RedAlert-IL/RedAlert-FiveM#1]

**Comment by MatanGaming** [comment]
?

**Comment by Danielb23451** [comment]
היי מתן,
בדקתי את הבעיה שציינת וראיתי שהבוט כן מוחק את ההתראה והוא מאפס לאחר זמן מה. נסה בבקשה להוריד מחדש את התוסף, אם עדיין ימשיך הבעיה, אנא פנה עליי בפרטי בדיסקורד אני אבדוק את זה יותר
